on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@main
        - uses: docker/login-action@master
          with:
              username: chaowenguo
              password: ${{secrets.DOCKER}}
        - uses: docker/setup-buildx-action@master
        - uses: docker/build-push-action@master
          with:
              push: true
              tags: chaowenguo/postgres
