on: push
    
jobs:
    backup:
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        steps:
        - uses: actions/checkout@main
        - run: |
              git pull --unshallow
              echo '${{secrets.KEY}}' > key
              chmod 400 key
              git -c core.sshCommand='ssh -i key -o StrictHostKeyChecking=no' push -f git@bitbucket.org:chaowenguo/${GITHUB_REPOSITORY#*/}
    build:
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-python@main
          with:
              python-version: 3.x
        - uses: actions/setup-node@main
          with:
              node-version: 18.x
        - run: |
              docker login -u chaowenguo -p ${{secrets.DOCKER}}
              docker build -t chaowenguo/postgres .
              docker push chaowenguo/postgres
              #wget https://download.oracle.com/otn_software/linux/instantclient/213000/oracle-instantclient-basic-21.3.0.0.0-1.el8.x86_64.rpm https://download.oracle.com/otn_software/linux/instantclient/213000/oracle-instantclient-sqlplus-21.3.0.0.0-1.el8.x86_64.rpm https://download.oracle.com/otn_software/linux/instantclient/213000/oracle-instantclient-devel-21.3.0.0.0-1.el8.x86_64.rpm
              #sudo apt update
              #sudo apt install -y --no-install-recommends alien
              #sudo alien -i *.x86_64.rpm
              #export ORACLE_HOME=/usr/lib/oracle/21/client64
              #export LD_LIBRARY_PATH=$ORACLE_HOME/lib/$LD_LIBRARY_PATH
              #pip install aiohttp asyncpg asyncmy oci cx_Oracle
              #echo '${{secrets.OCI}}' > oci.key
              #python build.py ${{secrets.CLIENTID}} ${{secrets.CLIENTSECRET}} ${{secrets.TENANTID}}
              curl https://bitbucket.org/chaowenguo/common/raw/main/package.json > package.json
              npm install node-fetch
              node build.js
    databaseConnect:
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        steps:
        - uses: actions/checkout@main
        - run: |
              echo '${{secrets.KEY}}' > key
              chmod 400 key
              git -c core.sshCommand='ssh -i key -o StrictHostKeyChecking=no' clone git@bitbucket.org:chaowenguo/key keykey
              mv keykey/certs .
              rm -rf keykey
              curl https://binaries.cockroachdb.com/cockroach-v22.1.4.linux-amd64.tgz | tar -xz
              sudo cp cockroach*/cockroach /usr/local/bin
              sudo cp -r cockroach*/lib /usr/local
              chmod 400 certs/client.root.key
              ips=$(curl https://bitbucket.org/chaowenguo/server/raw/main/server.json | sed -e s/,/\ /g -e s/[][\"]//g)
              array=($ips)
              cockroach init --certs-dir certs --host ${array[0]}
              cockroach sql --certs-dir certs --host ${array[0]} -d defaultdb -f database.sql
              sudo apt update
              sudo apt install -y --no-install-recommends redis-tools
              redis-cli --cluster create $(echo $ips | sed -e s/\ /:6379\ /g -e s/$/:6379/g) --cluster-yes -a ${{secrets.PASSWORD}}
              #https://www.cockroachlabs.com/docs/stable/deploy-cockroachdb-on-premises.html#step-9-scale-the-cluster
              #Redis cluster tutorial add new node
    clean:
        runs-on: ubuntu-latest
        permissions:
            actions: write
        steps:
        - uses: actions/setup-python@main
          with:
              python-version: 3.x
        - run: |
              pip install aiohttp
              curl https://bitbucket.org/chaowenguo/common/raw/main/clean.py | python - ${{secrets.GITHUB_TOKEN}}
