on:
    push:
    schedule:
    - cron: '0 1 * * *'
    
jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-python@main
          with:
              python-version: 3.x
        - run: |
              docker login -u chaowenguo -p ${{secrets.DOCKER}}
              docker build -t chaowenguo/postgres .
              docker push chaowenguo/postgres
              #wget https://download.oracle.com/otn_software/linux/instantclient/213000/oracle-instantclient-basic-21.3.0.0.0-1.el8.x86_64.rpm https://download.oracle.com/otn_software/linux/instantclient/213000/oracle-instantclient-sqlplus-21.3.0.0.0-1.el8.x86_64.rpm https://download.oracle.com/otn_software/linux/instantclient/213000/oracle-instantclient-devel-21.3.0.0.0-1.el8.x86_64.rpm
              #sudo apt update
              #sudo apt install -y --no-install-recommends alien
              #sudo alien -i *.x86_64.rpm
              #export ORACLE_HOME=/usr/lib/oracle/21/client64
              #export LD_LIBRARY_PATH=$ORACLE_HOME/lib/$LD_LIBRARY_PATH
              #pip install aiohttp asyncpg asyncmy oci cx_Oracle
              #echo '${{secrets.OCI}}' > oci.key
              #python build.py ${{secrets.CLIENTID}} ${{secrets.CLIENTSECRET}} ${{secrets.TENANTID}}
    cockroach:
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        steps:
        - uses: actions/checkout@main
        - run: |
              curl https://${{secrets.GITHUB}}@raw.githubusercontent.com/chaowenGUO/server/main/key > key
              chmod 400 key
              curl https://binaries.cockroachdb.com/cockroach-v21.2.7.linux-amd64.tgz | tar -xz
              sudo cp cockroach*/cockroach /usr/local/bin
              sudo cp -r cockroach*/lib /usr/local
              mkdir certs
              mkdir my-safe-directory
              cockroach cert create-ca --certs-dir certs --ca-key my-safe-directory/ca.key
              for i in 40.118.245.62 20.112.94.147 155.248.198.227
              do
                  cockroach cert create-node $i --certs-dir certs --ca-key my-safe-directory/ca.key
                  scp -o StrictHostKeyChecking=no -i key -r certs ubuntu@$i:
                  rm -rf certs/node*
              done
              cockroach cert create-client root --certs-dir certs --ca-key my-safe-directory/ca.key
              git add certs
              git config user.name dummy
              git config user.email dummy
              git commit --allow-empty-message -m ''
              git push
    clean:
        runs-on: ubuntu-latest
        if: github.event.schedule == '0 1 * * *'
        steps:
        - uses: actions/setup-python@main
          with:
              python-version: 3.x
        - run: |
              pip install aiohttp
              curl https://${GITHUB_REPOSITORY%/*}.github.io/common/clean.py | python - ${{secrets.GITHUB_TOKEN}}              
